/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "jobs.pb-c.h"
void   nfs_read_cmd__init
                     (NfsReadCmd         *message)
{
  static NfsReadCmd init_value = NFS_READ_CMD__INIT;
  *message = init_value;
}
size_t nfs_read_cmd__get_packed_size
                     (const NfsReadCmd *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_read_cmd__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs_read_cmd__pack
                     (const NfsReadCmd *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_read_cmd__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs_read_cmd__pack_to_buffer
                     (const NfsReadCmd *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_read_cmd__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NfsReadCmd *
       nfs_read_cmd__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NfsReadCmd *)
     protobuf_c_message_unpack (&nfs_read_cmd__descriptor,
                                allocator, len, data);
}
void   nfs_read_cmd__free_unpacked
                     (NfsReadCmd *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_read_cmd__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nfs_data__init
                     (NfsData         *message)
{
  static NfsData init_value = NFS_DATA__INIT;
  *message = init_value;
}
size_t nfs_data__get_packed_size
                     (const NfsData *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs_data__pack
                     (const NfsData *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs_data__pack_to_buffer
                     (const NfsData *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NfsData *
       nfs_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NfsData *)
     protobuf_c_message_unpack (&nfs_data__descriptor,
                                allocator, len, data);
}
void   nfs_data__free_unpacked
                     (NfsData *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nfs_write_cmd__init
                     (NfsWriteCmd         *message)
{
  static NfsWriteCmd init_value = NFS_WRITE_CMD__INIT;
  *message = init_value;
}
size_t nfs_write_cmd__get_packed_size
                     (const NfsWriteCmd *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_write_cmd__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs_write_cmd__pack
                     (const NfsWriteCmd *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_write_cmd__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs_write_cmd__pack_to_buffer
                     (const NfsWriteCmd *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_write_cmd__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NfsWriteCmd *
       nfs_write_cmd__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NfsWriteCmd *)
     protobuf_c_message_unpack (&nfs_write_cmd__descriptor,
                                allocator, len, data);
}
void   nfs_write_cmd__free_unpacked
                     (NfsWriteCmd *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_write_cmd__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nfs_create_cmd__init
                     (NfsCreateCmd         *message)
{
  static NfsCreateCmd init_value = NFS_CREATE_CMD__INIT;
  *message = init_value;
}
size_t nfs_create_cmd__get_packed_size
                     (const NfsCreateCmd *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_create_cmd__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs_create_cmd__pack
                     (const NfsCreateCmd *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_create_cmd__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs_create_cmd__pack_to_buffer
                     (const NfsCreateCmd *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_create_cmd__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NfsCreateCmd *
       nfs_create_cmd__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NfsCreateCmd *)
     protobuf_c_message_unpack (&nfs_create_cmd__descriptor,
                                allocator, len, data);
}
void   nfs_create_cmd__free_unpacked
                     (NfsCreateCmd *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_create_cmd__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nfs_access_cmd__init
                     (NfsAccessCmd         *message)
{
  static NfsAccessCmd init_value = NFS_ACCESS_CMD__INIT;
  *message = init_value;
}
size_t nfs_access_cmd__get_packed_size
                     (const NfsAccessCmd *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_access_cmd__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs_access_cmd__pack
                     (const NfsAccessCmd *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_access_cmd__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs_access_cmd__pack_to_buffer
                     (const NfsAccessCmd *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_access_cmd__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NfsAccessCmd *
       nfs_access_cmd__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NfsAccessCmd *)
     protobuf_c_message_unpack (&nfs_access_cmd__descriptor,
                                allocator, len, data);
}
void   nfs_access_cmd__free_unpacked
                     (NfsAccessCmd *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_access_cmd__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nfs_rename_cmd__init
                     (NfsRenameCmd         *message)
{
  static NfsRenameCmd init_value = NFS_RENAME_CMD__INIT;
  *message = init_value;
}
size_t nfs_rename_cmd__get_packed_size
                     (const NfsRenameCmd *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_rename_cmd__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs_rename_cmd__pack
                     (const NfsRenameCmd *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_rename_cmd__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs_rename_cmd__pack_to_buffer
                     (const NfsRenameCmd *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_rename_cmd__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NfsRenameCmd *
       nfs_rename_cmd__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NfsRenameCmd *)
     protobuf_c_message_unpack (&nfs_rename_cmd__descriptor,
                                allocator, len, data);
}
void   nfs_rename_cmd__free_unpacked
                     (NfsRenameCmd *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_rename_cmd__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nfs_commit_cmd__init
                     (NfsCommitCmd         *message)
{
  static NfsCommitCmd init_value = NFS_COMMIT_CMD__INIT;
  *message = init_value;
}
size_t nfs_commit_cmd__get_packed_size
                     (const NfsCommitCmd *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_commit_cmd__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs_commit_cmd__pack
                     (const NfsCommitCmd *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_commit_cmd__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs_commit_cmd__pack_to_buffer
                     (const NfsCommitCmd *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_commit_cmd__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NfsCommitCmd *
       nfs_commit_cmd__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NfsCommitCmd *)
     protobuf_c_message_unpack (&nfs_commit_cmd__descriptor,
                                allocator, len, data);
}
void   nfs_commit_cmd__free_unpacked
                     (NfsCommitCmd *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_commit_cmd__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sstack_nfs_command_struct__init
                     (SstackNfsCommandStruct         *message)
{
  static SstackNfsCommandStruct init_value = SSTACK_NFS_COMMAND_STRUCT__INIT;
  *message = init_value;
}
size_t sstack_nfs_command_struct__get_packed_size
                     (const SstackNfsCommandStruct *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sstack_nfs_command_struct__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sstack_nfs_command_struct__pack
                     (const SstackNfsCommandStruct *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sstack_nfs_command_struct__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sstack_nfs_command_struct__pack_to_buffer
                     (const SstackNfsCommandStruct *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sstack_nfs_command_struct__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SstackNfsCommandStruct *
       sstack_nfs_command_struct__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SstackNfsCommandStruct *)
     protobuf_c_message_unpack (&sstack_nfs_command_struct__descriptor,
                                allocator, len, data);
}
void   sstack_nfs_command_struct__free_unpacked
                     (SstackNfsCommandStruct *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sstack_nfs_command_struct__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nfs_lookup_resp__init
                     (NfsLookupResp         *message)
{
  static NfsLookupResp init_value = NFS_LOOKUP_RESP__INIT;
  *message = init_value;
}
size_t nfs_lookup_resp__get_packed_size
                     (const NfsLookupResp *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_lookup_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs_lookup_resp__pack
                     (const NfsLookupResp *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_lookup_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs_lookup_resp__pack_to_buffer
                     (const NfsLookupResp *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_lookup_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NfsLookupResp *
       nfs_lookup_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NfsLookupResp *)
     protobuf_c_message_unpack (&nfs_lookup_resp__descriptor,
                                allocator, len, data);
}
void   nfs_lookup_resp__free_unpacked
                     (NfsLookupResp *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_lookup_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nfs_access_resp__init
                     (NfsAccessResp         *message)
{
  static NfsAccessResp init_value = NFS_ACCESS_RESP__INIT;
  *message = init_value;
}
size_t nfs_access_resp__get_packed_size
                     (const NfsAccessResp *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_access_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs_access_resp__pack
                     (const NfsAccessResp *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_access_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs_access_resp__pack_to_buffer
                     (const NfsAccessResp *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_access_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NfsAccessResp *
       nfs_access_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NfsAccessResp *)
     protobuf_c_message_unpack (&nfs_access_resp__descriptor,
                                allocator, len, data);
}
void   nfs_access_resp__free_unpacked
                     (NfsAccessResp *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_access_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nfs_read_resp__init
                     (NfsReadResp         *message)
{
  static NfsReadResp init_value = NFS_READ_RESP__INIT;
  *message = init_value;
}
size_t nfs_read_resp__get_packed_size
                     (const NfsReadResp *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_read_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs_read_resp__pack
                     (const NfsReadResp *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_read_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs_read_resp__pack_to_buffer
                     (const NfsReadResp *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_read_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NfsReadResp *
       nfs_read_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NfsReadResp *)
     protobuf_c_message_unpack (&nfs_read_resp__descriptor,
                                allocator, len, data);
}
void   nfs_read_resp__free_unpacked
                     (NfsReadResp *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_read_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nfs_write_resp__init
                     (NfsWriteResp         *message)
{
  static NfsWriteResp init_value = NFS_WRITE_RESP__INIT;
  *message = init_value;
}
size_t nfs_write_resp__get_packed_size
                     (const NfsWriteResp *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_write_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs_write_resp__pack
                     (const NfsWriteResp *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_write_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs_write_resp__pack_to_buffer
                     (const NfsWriteResp *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_write_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NfsWriteResp *
       nfs_write_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NfsWriteResp *)
     protobuf_c_message_unpack (&nfs_write_resp__descriptor,
                                allocator, len, data);
}
void   nfs_write_resp__free_unpacked
                     (NfsWriteResp *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_write_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nfs_create_resp__init
                     (NfsCreateResp         *message)
{
  static NfsCreateResp init_value = NFS_CREATE_RESP__INIT;
  *message = init_value;
}
size_t nfs_create_resp__get_packed_size
                     (const NfsCreateResp *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_create_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs_create_resp__pack
                     (const NfsCreateResp *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_create_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs_create_resp__pack_to_buffer
                     (const NfsCreateResp *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_create_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NfsCreateResp *
       nfs_create_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NfsCreateResp *)
     protobuf_c_message_unpack (&nfs_create_resp__descriptor,
                                allocator, len, data);
}
void   nfs_create_resp__free_unpacked
                     (NfsCreateResp *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_create_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nfs_remove_resp__init
                     (NfsRemoveResp         *message)
{
  static NfsRemoveResp init_value = NFS_REMOVE_RESP__INIT;
  *message = init_value;
}
size_t nfs_remove_resp__get_packed_size
                     (const NfsRemoveResp *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_remove_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs_remove_resp__pack
                     (const NfsRemoveResp *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_remove_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs_remove_resp__pack_to_buffer
                     (const NfsRemoveResp *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_remove_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NfsRemoveResp *
       nfs_remove_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NfsRemoveResp *)
     protobuf_c_message_unpack (&nfs_remove_resp__descriptor,
                                allocator, len, data);
}
void   nfs_remove_resp__free_unpacked
                     (NfsRemoveResp *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_remove_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nfs_rename_resp__init
                     (NfsRenameResp         *message)
{
  static NfsRenameResp init_value = NFS_RENAME_RESP__INIT;
  *message = init_value;
}
size_t nfs_rename_resp__get_packed_size
                     (const NfsRenameResp *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_rename_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs_rename_resp__pack
                     (const NfsRenameResp *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_rename_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs_rename_resp__pack_to_buffer
                     (const NfsRenameResp *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_rename_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NfsRenameResp *
       nfs_rename_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NfsRenameResp *)
     protobuf_c_message_unpack (&nfs_rename_resp__descriptor,
                                allocator, len, data);
}
void   nfs_rename_resp__free_unpacked
                     (NfsRenameResp *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_rename_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nfs_fsstat_resp__init
                     (NfsFsstatResp         *message)
{
  static NfsFsstatResp init_value = NFS_FSSTAT_RESP__INIT;
  *message = init_value;
}
size_t nfs_fsstat_resp__get_packed_size
                     (const NfsFsstatResp *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_fsstat_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs_fsstat_resp__pack
                     (const NfsFsstatResp *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_fsstat_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs_fsstat_resp__pack_to_buffer
                     (const NfsFsstatResp *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_fsstat_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NfsFsstatResp *
       nfs_fsstat_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NfsFsstatResp *)
     protobuf_c_message_unpack (&nfs_fsstat_resp__descriptor,
                                allocator, len, data);
}
void   nfs_fsstat_resp__free_unpacked
                     (NfsFsstatResp *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_fsstat_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nfs_fsinfo_resp__init
                     (NfsFsinfoResp         *message)
{
  static NfsFsinfoResp init_value = NFS_FSINFO_RESP__INIT;
  *message = init_value;
}
size_t nfs_fsinfo_resp__get_packed_size
                     (const NfsFsinfoResp *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_fsinfo_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs_fsinfo_resp__pack
                     (const NfsFsinfoResp *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_fsinfo_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs_fsinfo_resp__pack_to_buffer
                     (const NfsFsinfoResp *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_fsinfo_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NfsFsinfoResp *
       nfs_fsinfo_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NfsFsinfoResp *)
     protobuf_c_message_unpack (&nfs_fsinfo_resp__descriptor,
                                allocator, len, data);
}
void   nfs_fsinfo_resp__free_unpacked
                     (NfsFsinfoResp *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_fsinfo_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nfs_pathconf_resp__init
                     (NfsPathconfResp         *message)
{
  static NfsPathconfResp init_value = NFS_PATHCONF_RESP__INIT;
  *message = init_value;
}
size_t nfs_pathconf_resp__get_packed_size
                     (const NfsPathconfResp *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_pathconf_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs_pathconf_resp__pack
                     (const NfsPathconfResp *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_pathconf_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs_pathconf_resp__pack_to_buffer
                     (const NfsPathconfResp *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_pathconf_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NfsPathconfResp *
       nfs_pathconf_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NfsPathconfResp *)
     protobuf_c_message_unpack (&nfs_pathconf_resp__descriptor,
                                allocator, len, data);
}
void   nfs_pathconf_resp__free_unpacked
                     (NfsPathconfResp *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_pathconf_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nfs_commit_resp__init
                     (NfsCommitResp         *message)
{
  static NfsCommitResp init_value = NFS_COMMIT_RESP__INIT;
  *message = init_value;
}
size_t nfs_commit_resp__get_packed_size
                     (const NfsCommitResp *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_commit_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs_commit_resp__pack
                     (const NfsCommitResp *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_commit_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs_commit_resp__pack_to_buffer
                     (const NfsCommitResp *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_commit_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NfsCommitResp *
       nfs_commit_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NfsCommitResp *)
     protobuf_c_message_unpack (&nfs_commit_resp__descriptor,
                                allocator, len, data);
}
void   nfs_commit_resp__free_unpacked
                     (NfsCommitResp *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nfs_commit_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sstack_nfs_result_struct__init
                     (SstackNfsResultStruct         *message)
{
  static SstackNfsResultStruct init_value = SSTACK_NFS_RESULT_STRUCT__INIT;
  *message = init_value;
}
size_t sstack_nfs_result_struct__get_packed_size
                     (const SstackNfsResultStruct *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sstack_nfs_result_struct__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sstack_nfs_result_struct__pack
                     (const SstackNfsResultStruct *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sstack_nfs_result_struct__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sstack_nfs_result_struct__pack_to_buffer
                     (const SstackNfsResultStruct *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sstack_nfs_result_struct__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SstackNfsResultStruct *
       sstack_nfs_result_struct__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SstackNfsResultStruct *)
     protobuf_c_message_unpack (&sstack_nfs_result_struct__descriptor,
                                allocator, len, data);
}
void   sstack_nfs_result_struct__free_unpacked
                     (SstackNfsResultStruct *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sstack_nfs_result_struct__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sstack_payload_hdr_t__init
                     (SstackPayloadHdrT         *message)
{
  static SstackPayloadHdrT init_value = SSTACK_PAYLOAD_HDR_T__INIT;
  *message = init_value;
}
size_t sstack_payload_hdr_t__get_packed_size
                     (const SstackPayloadHdrT *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sstack_payload_hdr_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sstack_payload_hdr_t__pack
                     (const SstackPayloadHdrT *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sstack_payload_hdr_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sstack_payload_hdr_t__pack_to_buffer
                     (const SstackPayloadHdrT *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sstack_payload_hdr_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SstackPayloadHdrT *
       sstack_payload_hdr_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SstackPayloadHdrT *)
     protobuf_c_message_unpack (&sstack_payload_hdr_t__descriptor,
                                allocator, len, data);
}
void   sstack_payload_hdr_t__free_unpacked
                     (SstackPayloadHdrT *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sstack_payload_hdr_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sstack_payload_t__init
                     (SstackPayloadT         *message)
{
  static SstackPayloadT init_value = SSTACK_PAYLOAD_T__INIT;
  *message = init_value;
}
size_t sstack_payload_t__get_packed_size
                     (const SstackPayloadT *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sstack_payload_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sstack_payload_t__pack
                     (const SstackPayloadT *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sstack_payload_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sstack_payload_t__pack_to_buffer
                     (const SstackPayloadT *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sstack_payload_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SstackPayloadT *
       sstack_payload_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SstackPayloadT *)
     protobuf_c_message_unpack (&sstack_payload_t__descriptor,
                                allocator, len, data);
}
void   sstack_payload_t__free_unpacked
                     (SstackPayloadT *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sstack_payload_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor nfs_read_cmd__field_descriptors[3] =
{
  {
    "offset",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NfsReadCmd, offset),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NfsReadCmd, count),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NfsReadCmd, data),
    &nfs_data__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nfs_read_cmd__field_indices_by_name[] = {
  1,   /* field[1] = count */
  2,   /* field[2] = data */
  0,   /* field[0] = offset */
};
static const ProtobufCIntRange nfs_read_cmd__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor nfs_read_cmd__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "nfs_read_cmd",
  "NfsReadCmd",
  "NfsReadCmd",
  "",
  sizeof(NfsReadCmd),
  3,
  nfs_read_cmd__field_descriptors,
  nfs_read_cmd__field_indices_by_name,
  1,  nfs_read_cmd__number_ranges,
  (ProtobufCMessageInit) nfs_read_cmd__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nfs_data__field_descriptors[2] =
{
  {
    "data_len",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NfsData, data_len),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data_val",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NfsData, data_val),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nfs_data__field_indices_by_name[] = {
  0,   /* field[0] = data_len */
  1,   /* field[1] = data_val */
};
static const ProtobufCIntRange nfs_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nfs_data__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "nfs_data",
  "NfsData",
  "NfsData",
  "",
  sizeof(NfsData),
  2,
  nfs_data__field_descriptors,
  nfs_data__field_indices_by_name,
  1,  nfs_data__number_ranges,
  (ProtobufCMessageInit) nfs_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nfs_write_cmd__field_descriptors[3] =
{
  {
    "offset",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NfsWriteCmd, offset),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NfsWriteCmd, count),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NfsWriteCmd, data),
    &nfs_data__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nfs_write_cmd__field_indices_by_name[] = {
  1,   /* field[1] = count */
  2,   /* field[2] = data */
  0,   /* field[0] = offset */
};
static const ProtobufCIntRange nfs_write_cmd__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor nfs_write_cmd__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "nfs_write_cmd",
  "NfsWriteCmd",
  "NfsWriteCmd",
  "",
  sizeof(NfsWriteCmd),
  3,
  nfs_write_cmd__field_descriptors,
  nfs_write_cmd__field_indices_by_name,
  1,  nfs_write_cmd__number_ranges,
  (ProtobufCMessageInit) nfs_write_cmd__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nfs_create_cmd__field_descriptors[2] =
{
  {
    "mode",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NfsCreateCmd, mode),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NfsCreateCmd, data),
    &nfs_data__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nfs_create_cmd__field_indices_by_name[] = {
  1,   /* field[1] = data */
  0,   /* field[0] = mode */
};
static const ProtobufCIntRange nfs_create_cmd__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nfs_create_cmd__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "nfs_create_cmd",
  "NfsCreateCmd",
  "NfsCreateCmd",
  "",
  sizeof(NfsCreateCmd),
  2,
  nfs_create_cmd__field_descriptors,
  nfs_create_cmd__field_indices_by_name,
  1,  nfs_create_cmd__number_ranges,
  (ProtobufCMessageInit) nfs_create_cmd__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nfs_access_cmd__field_descriptors[1] =
{
  {
    "mode",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NfsAccessCmd, mode),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nfs_access_cmd__field_indices_by_name[] = {
  0,   /* field[0] = mode */
};
static const ProtobufCIntRange nfs_access_cmd__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor nfs_access_cmd__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "nfs_access_cmd",
  "NfsAccessCmd",
  "NfsAccessCmd",
  "",
  sizeof(NfsAccessCmd),
  1,
  nfs_access_cmd__field_descriptors,
  nfs_access_cmd__field_indices_by_name,
  1,  nfs_access_cmd__number_ranges,
  (ProtobufCMessageInit) nfs_access_cmd__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nfs_rename_cmd__field_descriptors[1] =
{
  {
    "new_path",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NfsRenameCmd, new_path),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nfs_rename_cmd__field_indices_by_name[] = {
  0,   /* field[0] = new_path */
};
static const ProtobufCIntRange nfs_rename_cmd__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor nfs_rename_cmd__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "nfs_rename_cmd",
  "NfsRenameCmd",
  "NfsRenameCmd",
  "",
  sizeof(NfsRenameCmd),
  1,
  nfs_rename_cmd__field_descriptors,
  nfs_rename_cmd__field_indices_by_name,
  1,  nfs_rename_cmd__number_ranges,
  (ProtobufCMessageInit) nfs_rename_cmd__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nfs_commit_cmd__field_descriptors[2] =
{
  {
    "offset",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NfsCommitCmd, offset),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NfsCommitCmd, count),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nfs_commit_cmd__field_indices_by_name[] = {
  1,   /* field[1] = count */
  0,   /* field[0] = offset */
};
static const ProtobufCIntRange nfs_commit_cmd__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nfs_commit_cmd__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "nfs_commit_cmd",
  "NfsCommitCmd",
  "NfsCommitCmd",
  "",
  sizeof(NfsCommitCmd),
  2,
  nfs_commit_cmd__field_descriptors,
  nfs_commit_cmd__field_indices_by_name,
  1,  nfs_commit_cmd__number_ranges,
  (ProtobufCMessageInit) nfs_commit_cmd__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sstack_nfs_command_struct__field_descriptors[6] =
{
  {
    "read_cmd",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SstackNfsCommandStruct, read_cmd),
    &nfs_read_cmd__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "write_cmd",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SstackNfsCommandStruct, write_cmd),
    &nfs_write_cmd__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "create_cmd",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SstackNfsCommandStruct, create_cmd),
    &nfs_create_cmd__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "access_cmd",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SstackNfsCommandStruct, access_cmd),
    &nfs_access_cmd__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rename_cmd",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SstackNfsCommandStruct, rename_cmd),
    &nfs_rename_cmd__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "commit_cmd",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SstackNfsCommandStruct, commit_cmd),
    &nfs_commit_cmd__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sstack_nfs_command_struct__field_indices_by_name[] = {
  3,   /* field[3] = access_cmd */
  5,   /* field[5] = commit_cmd */
  2,   /* field[2] = create_cmd */
  0,   /* field[0] = read_cmd */
  4,   /* field[4] = rename_cmd */
  1,   /* field[1] = write_cmd */
};
static const ProtobufCIntRange sstack_nfs_command_struct__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor sstack_nfs_command_struct__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "sstack_nfs_command_struct",
  "SstackNfsCommandStruct",
  "SstackNfsCommandStruct",
  "",
  sizeof(SstackNfsCommandStruct),
  6,
  sstack_nfs_command_struct__field_descriptors,
  sstack_nfs_command_struct__field_indices_by_name,
  1,  sstack_nfs_command_struct__number_ranges,
  (ProtobufCMessageInit) sstack_nfs_command_struct__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nfs_lookup_resp__field_descriptors[1] =
{
  {
    "lookup_path",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NfsLookupResp, lookup_path),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nfs_lookup_resp__field_indices_by_name[] = {
  0,   /* field[0] = lookup_path */
};
static const ProtobufCIntRange nfs_lookup_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor nfs_lookup_resp__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "nfs_lookup_resp",
  "NfsLookupResp",
  "NfsLookupResp",
  "",
  sizeof(NfsLookupResp),
  1,
  nfs_lookup_resp__field_descriptors,
  nfs_lookup_resp__field_indices_by_name,
  1,  nfs_lookup_resp__number_ranges,
  (ProtobufCMessageInit) nfs_lookup_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nfs_access_resp__field_descriptors[1] =
{
  {
    "access",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NfsAccessResp, access),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nfs_access_resp__field_indices_by_name[] = {
  0,   /* field[0] = access */
};
static const ProtobufCIntRange nfs_access_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor nfs_access_resp__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "nfs_access_resp",
  "NfsAccessResp",
  "NfsAccessResp",
  "",
  sizeof(NfsAccessResp),
  1,
  nfs_access_resp__field_descriptors,
  nfs_access_resp__field_indices_by_name,
  1,  nfs_access_resp__number_ranges,
  (ProtobufCMessageInit) nfs_access_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nfs_read_resp__field_descriptors[3] =
{
  {
    "count",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NfsReadResp, count),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "eof",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NfsReadResp, eof),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NfsReadResp, data),
    &nfs_data__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nfs_read_resp__field_indices_by_name[] = {
  0,   /* field[0] = count */
  2,   /* field[2] = data */
  1,   /* field[1] = eof */
};
static const ProtobufCIntRange nfs_read_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor nfs_read_resp__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "nfs_read_resp",
  "NfsReadResp",
  "NfsReadResp",
  "",
  sizeof(NfsReadResp),
  3,
  nfs_read_resp__field_descriptors,
  nfs_read_resp__field_indices_by_name,
  1,  nfs_read_resp__number_ranges,
  (ProtobufCMessageInit) nfs_read_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nfs_write_resp__field_descriptors[2] =
{
  {
    "file_write_ok",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NfsWriteResp, file_write_ok),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "file_wc",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NfsWriteResp, file_wc),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nfs_write_resp__field_indices_by_name[] = {
  1,   /* field[1] = file_wc */
  0,   /* field[0] = file_write_ok */
};
static const ProtobufCIntRange nfs_write_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nfs_write_resp__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "nfs_write_resp",
  "NfsWriteResp",
  "NfsWriteResp",
  "",
  sizeof(NfsWriteResp),
  2,
  nfs_write_resp__field_descriptors,
  nfs_write_resp__field_indices_by_name,
  1,  nfs_write_resp__number_ranges,
  (ProtobufCMessageInit) nfs_write_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nfs_create_resp__field_descriptors[2] =
{
  {
    "file_create_ok",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NfsCreateResp, file_create_ok),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "file_wc",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NfsCreateResp, file_wc),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nfs_create_resp__field_indices_by_name[] = {
  0,   /* field[0] = file_create_ok */
  1,   /* field[1] = file_wc */
};
static const ProtobufCIntRange nfs_create_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nfs_create_resp__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "nfs_create_resp",
  "NfsCreateResp",
  "NfsCreateResp",
  "",
  sizeof(NfsCreateResp),
  2,
  nfs_create_resp__field_descriptors,
  nfs_create_resp__field_indices_by_name,
  1,  nfs_create_resp__number_ranges,
  (ProtobufCMessageInit) nfs_create_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nfs_remove_resp__field_descriptors[1] =
{
  {
    "file_remove_ok",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NfsRemoveResp, file_remove_ok),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nfs_remove_resp__field_indices_by_name[] = {
  0,   /* field[0] = file_remove_ok */
};
static const ProtobufCIntRange nfs_remove_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor nfs_remove_resp__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "nfs_remove_resp",
  "NfsRemoveResp",
  "NfsRemoveResp",
  "",
  sizeof(NfsRemoveResp),
  1,
  nfs_remove_resp__field_descriptors,
  nfs_remove_resp__field_indices_by_name,
  1,  nfs_remove_resp__number_ranges,
  (ProtobufCMessageInit) nfs_remove_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nfs_rename_resp__field_descriptors[1] =
{
  {
    "file_rename_ok",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NfsRenameResp, file_rename_ok),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nfs_rename_resp__field_indices_by_name[] = {
  0,   /* field[0] = file_rename_ok */
};
static const ProtobufCIntRange nfs_rename_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor nfs_rename_resp__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "nfs_rename_resp",
  "NfsRenameResp",
  "NfsRenameResp",
  "",
  sizeof(NfsRenameResp),
  1,
  nfs_rename_resp__field_descriptors,
  nfs_rename_resp__field_indices_by_name,
  1,  nfs_rename_resp__number_ranges,
  (ProtobufCMessageInit) nfs_rename_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nfs_fsstat_resp__field_descriptors[0] =
{
};
static const unsigned nfs_fsstat_resp__field_indices_by_name[] = {
};
#define nfs_fsstat_resp__number_ranges NULL
const ProtobufCMessageDescriptor nfs_fsstat_resp__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "nfs_fsstat_resp",
  "NfsFsstatResp",
  "NfsFsstatResp",
  "",
  sizeof(NfsFsstatResp),
  0,
  nfs_fsstat_resp__field_descriptors,
  nfs_fsstat_resp__field_indices_by_name,
  0,  nfs_fsstat_resp__number_ranges,
  (ProtobufCMessageInit) nfs_fsstat_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nfs_fsinfo_resp__field_descriptors[0] =
{
};
static const unsigned nfs_fsinfo_resp__field_indices_by_name[] = {
};
#define nfs_fsinfo_resp__number_ranges NULL
const ProtobufCMessageDescriptor nfs_fsinfo_resp__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "nfs_fsinfo_resp",
  "NfsFsinfoResp",
  "NfsFsinfoResp",
  "",
  sizeof(NfsFsinfoResp),
  0,
  nfs_fsinfo_resp__field_descriptors,
  nfs_fsinfo_resp__field_indices_by_name,
  0,  nfs_fsinfo_resp__number_ranges,
  (ProtobufCMessageInit) nfs_fsinfo_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nfs_pathconf_resp__field_descriptors[0] =
{
};
static const unsigned nfs_pathconf_resp__field_indices_by_name[] = {
};
#define nfs_pathconf_resp__number_ranges NULL
const ProtobufCMessageDescriptor nfs_pathconf_resp__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "nfs_pathconf_resp",
  "NfsPathconfResp",
  "NfsPathconfResp",
  "",
  sizeof(NfsPathconfResp),
  0,
  nfs_pathconf_resp__field_descriptors,
  nfs_pathconf_resp__field_indices_by_name,
  0,  nfs_pathconf_resp__number_ranges,
  (ProtobufCMessageInit) nfs_pathconf_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nfs_commit_resp__field_descriptors[0] =
{
};
static const unsigned nfs_commit_resp__field_indices_by_name[] = {
};
#define nfs_commit_resp__number_ranges NULL
const ProtobufCMessageDescriptor nfs_commit_resp__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "nfs_commit_resp",
  "NfsCommitResp",
  "NfsCommitResp",
  "",
  sizeof(NfsCommitResp),
  0,
  nfs_commit_resp__field_descriptors,
  nfs_commit_resp__field_indices_by_name,
  0,  nfs_commit_resp__number_ranges,
  (ProtobufCMessageInit) nfs_commit_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sstack_nfs_result_struct__field_descriptors[11] =
{
  {
    "lookup_resp",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SstackNfsResultStruct, lookup_resp),
    &nfs_lookup_resp__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "access_resp",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SstackNfsResultStruct, access_resp),
    &nfs_access_resp__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "read_resp",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SstackNfsResultStruct, read_resp),
    &nfs_read_resp__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "write_resp",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SstackNfsResultStruct, write_resp),
    &nfs_write_resp__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "create_resp",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SstackNfsResultStruct, create_resp),
    &nfs_create_resp__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "remove_resp",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SstackNfsResultStruct, remove_resp),
    &nfs_remove_resp__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rename_resp",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SstackNfsResultStruct, rename_resp),
    &nfs_rename_resp__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fsstat_resp",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SstackNfsResultStruct, fsstat_resp),
    &nfs_fsstat_resp__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fsinfo_resp",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SstackNfsResultStruct, fsinfo_resp),
    &nfs_fsinfo_resp__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pathconf_resp",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SstackNfsResultStruct, pathconf_resp),
    &nfs_pathconf_resp__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "commit_resp",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SstackNfsResultStruct, commit_resp),
    &nfs_commit_resp__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sstack_nfs_result_struct__field_indices_by_name[] = {
  1,   /* field[1] = access_resp */
  10,   /* field[10] = commit_resp */
  4,   /* field[4] = create_resp */
  8,   /* field[8] = fsinfo_resp */
  7,   /* field[7] = fsstat_resp */
  0,   /* field[0] = lookup_resp */
  9,   /* field[9] = pathconf_resp */
  2,   /* field[2] = read_resp */
  5,   /* field[5] = remove_resp */
  6,   /* field[6] = rename_resp */
  3,   /* field[3] = write_resp */
};
static const ProtobufCIntRange sstack_nfs_result_struct__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor sstack_nfs_result_struct__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "sstack_nfs_result_struct",
  "SstackNfsResultStruct",
  "SstackNfsResultStruct",
  "",
  sizeof(SstackNfsResultStruct),
  11,
  sstack_nfs_result_struct__field_descriptors,
  sstack_nfs_result_struct__field_indices_by_name,
  1,  sstack_nfs_result_struct__number_ranges,
  (ProtobufCMessageInit) sstack_nfs_result_struct__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sstack_payload_hdr_t__field_descriptors[2] =
{
  {
    "sequence",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SstackPayloadHdrT, sequence),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload_len",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SstackPayloadHdrT, payload_len),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sstack_payload_hdr_t__field_indices_by_name[] = {
  1,   /* field[1] = payload_len */
  0,   /* field[0] = sequence */
};
static const ProtobufCIntRange sstack_payload_hdr_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sstack_payload_hdr_t__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "sstack_payload_hdr_t",
  "SstackPayloadHdrT",
  "SstackPayloadHdrT",
  "",
  sizeof(SstackPayloadHdrT),
  2,
  sstack_payload_hdr_t__field_descriptors,
  sstack_payload_hdr_t__field_indices_by_name,
  1,  sstack_payload_hdr_t__number_ranges,
  (ProtobufCMessageInit) sstack_payload_hdr_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue sstack_payload_t__sstack_nfs_command_t__enum_values_by_number[21] =
{
  { "NFS_GETATTR", "SSTACK_PAYLOAD_T__SSTACK_NFS_COMMAND_T__NFS_GETATTR", 1 },
  { "NFS_SETATTR", "SSTACK_PAYLOAD_T__SSTACK_NFS_COMMAND_T__NFS_SETATTR", 2 },
  { "NFS_LOOKUP", "SSTACK_PAYLOAD_T__SSTACK_NFS_COMMAND_T__NFS_LOOKUP", 3 },
  { "NFS_ACCESS", "SSTACK_PAYLOAD_T__SSTACK_NFS_COMMAND_T__NFS_ACCESS", 4 },
  { "NFS_READLINK", "SSTACK_PAYLOAD_T__SSTACK_NFS_COMMAND_T__NFS_READLINK", 5 },
  { "NFS_READ", "SSTACK_PAYLOAD_T__SSTACK_NFS_COMMAND_T__NFS_READ", 6 },
  { "NFS_WRITE", "SSTACK_PAYLOAD_T__SSTACK_NFS_COMMAND_T__NFS_WRITE", 7 },
  { "NFS_CREATE", "SSTACK_PAYLOAD_T__SSTACK_NFS_COMMAND_T__NFS_CREATE", 8 },
  { "NFS_MKDIR", "SSTACK_PAYLOAD_T__SSTACK_NFS_COMMAND_T__NFS_MKDIR", 9 },
  { "NFS_SYMLINK", "SSTACK_PAYLOAD_T__SSTACK_NFS_COMMAND_T__NFS_SYMLINK", 10 },
  { "NFS_MKNOD", "SSTACK_PAYLOAD_T__SSTACK_NFS_COMMAND_T__NFS_MKNOD", 11 },
  { "NFS_REMOVE", "SSTACK_PAYLOAD_T__SSTACK_NFS_COMMAND_T__NFS_REMOVE", 12 },
  { "NFS_RMDIR", "SSTACK_PAYLOAD_T__SSTACK_NFS_COMMAND_T__NFS_RMDIR", 13 },
  { "NFS_RENAME", "SSTACK_PAYLOAD_T__SSTACK_NFS_COMMAND_T__NFS_RENAME", 14 },
  { "NFS_LINK", "SSTACK_PAYLOAD_T__SSTACK_NFS_COMMAND_T__NFS_LINK", 15 },
  { "NFS_READDIR", "SSTACK_PAYLOAD_T__SSTACK_NFS_COMMAND_T__NFS_READDIR", 16 },
  { "NFS_READDIRPLUS", "SSTACK_PAYLOAD_T__SSTACK_NFS_COMMAND_T__NFS_READDIRPLUS", 17 },
  { "NFS_FSSTAT", "SSTACK_PAYLOAD_T__SSTACK_NFS_COMMAND_T__NFS_FSSTAT", 18 },
  { "NFS_FSINFO", "SSTACK_PAYLOAD_T__SSTACK_NFS_COMMAND_T__NFS_FSINFO", 19 },
  { "NFS_PATHCONF", "SSTACK_PAYLOAD_T__SSTACK_NFS_COMMAND_T__NFS_PATHCONF", 20 },
  { "NFS_COMMIT", "SSTACK_PAYLOAD_T__SSTACK_NFS_COMMAND_T__NFS_COMMIT", 21 },
};
static const ProtobufCIntRange sstack_payload_t__sstack_nfs_command_t__value_ranges[] = {
{1, 0},{0, 21}
};
const ProtobufCEnumValueIndex sstack_payload_t__sstack_nfs_command_t__enum_values_by_name[22] =
{
  { "NFS_ACCESS", 3 },
  { "NFS_COMMIT", 20 },
  { "NFS_CREATE", 7 },
  { "NFS_FSINFO", 18 },
  { "NFS_FSSTAT", 17 },
  { "NFS_GETATTR", 0 },
  { "NFS_LINK", 14 },
  { "NFS_LOOKUP", 2 },
  { "NFS_MKDIR", 8 },
  { "NFS_MKNOD", 10 },
  { "NFS_PATHCONF", 19 },
  { "NFS_READ", 5 },
  { "NFS_READDIR", 15 },
  { "NFS_READDIRPLUS", 16 },
  { "NFS_READLINK", 4 },
  { "NFS_REMOVE", 11 },
  { "NFS_RENAME", 13 },
  { "NFS_RMDIR", 12 },
  { "NFS_SETATTR", 1 },
  { "NFS_SYMLINK", 9 },
  { "NFS_VALID_MAX", 20 },
  { "NFS_WRITE", 6 },
};
const ProtobufCEnumDescriptor sstack_payload_t__sstack_nfs_command_t__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "sstack_payload_t.sstack_nfs_command_t",
  "sstack_nfs_command_t",
  "SstackPayloadT__SstackNfsCommandT",
  "",
  21,
  sstack_payload_t__sstack_nfs_command_t__enum_values_by_number,
  22,
  sstack_payload_t__sstack_nfs_command_t__enum_values_by_name,
  1,
  sstack_payload_t__sstack_nfs_command_t__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor sstack_payload_t__field_descriptors[4] =
{
  {
    "hdr",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SstackPayloadT, hdr),
    &sstack_payload_hdr_t__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "command",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SstackPayloadT, command),
    &sstack_payload_t__sstack_nfs_command_t__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "command_struct",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SstackPayloadT, command_struct),
    &sstack_nfs_command_struct__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "result_struct",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SstackPayloadT, result_struct),
    &sstack_nfs_result_struct__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sstack_payload_t__field_indices_by_name[] = {
  1,   /* field[1] = command */
  2,   /* field[2] = command_struct */
  0,   /* field[0] = hdr */
  3,   /* field[3] = result_struct */
};
static const ProtobufCIntRange sstack_payload_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor sstack_payload_t__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "sstack_payload_t",
  "SstackPayloadT",
  "SstackPayloadT",
  "",
  sizeof(SstackPayloadT),
  4,
  sstack_payload_t__field_descriptors,
  sstack_payload_t__field_indices_by_name,
  1,  sstack_payload_t__number_ranges,
  (ProtobufCMessageInit) sstack_payload_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
