/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "cli.pb-c.h"
void   sfs_client_request_hdr__init
                     (SfsClientRequestHdr         *message)
{
  static SfsClientRequestHdr init_value = SFS_CLIENT_REQUEST_HDR__INIT;
  *message = init_value;
}
size_t sfs_client_request_hdr__get_packed_size
                     (const SfsClientRequestHdr *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sfs_client_request_hdr__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sfs_client_request_hdr__pack
                     (const SfsClientRequestHdr *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sfs_client_request_hdr__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sfs_client_request_hdr__pack_to_buffer
                     (const SfsClientRequestHdr *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sfs_client_request_hdr__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SfsClientRequestHdr *
       sfs_client_request_hdr__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SfsClientRequestHdr *)
     protobuf_c_message_unpack (&sfs_client_request_hdr__descriptor,
                                allocator, len, data);
}
void   sfs_client_request_hdr__free_unpacked
                     (SfsClientRequestHdr *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sfs_client_request_hdr__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   branch_struct_cli__init
                     (BranchStructCli         *message)
{
  static BranchStructCli init_value = BRANCH_STRUCT_CLI__INIT;
  *message = init_value;
}
size_t branch_struct_cli__get_packed_size
                     (const BranchStructCli *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &branch_struct_cli__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t branch_struct_cli__pack
                     (const BranchStructCli *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &branch_struct_cli__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t branch_struct_cli__pack_to_buffer
                     (const BranchStructCli *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &branch_struct_cli__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BranchStructCli *
       branch_struct_cli__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BranchStructCli *)
     protobuf_c_message_unpack (&branch_struct_cli__descriptor,
                                allocator, len, data);
}
void   branch_struct_cli__free_unpacked
                     (BranchStructCli *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &branch_struct_cli__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   policy_struct_cli__init
                     (PolicyStructCli         *message)
{
  static PolicyStructCli init_value = POLICY_STRUCT_CLI__INIT;
  *message = init_value;
}
size_t policy_struct_cli__get_packed_size
                     (const PolicyStructCli *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &policy_struct_cli__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t policy_struct_cli__pack
                     (const PolicyStructCli *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &policy_struct_cli__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t policy_struct_cli__pack_to_buffer
                     (const PolicyStructCli *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &policy_struct_cli__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PolicyStructCli *
       policy_struct_cli__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PolicyStructCli *)
     protobuf_c_message_unpack (&policy_struct_cli__descriptor,
                                allocator, len, data);
}
void   policy_struct_cli__free_unpacked
                     (PolicyStructCli *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &policy_struct_cli__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sfs_client_request_t__init
                     (SfsClientRequestT         *message)
{
  static SfsClientRequestT init_value = SFS_CLIENT_REQUEST_T__INIT;
  *message = init_value;
}
size_t sfs_client_request_t__get_packed_size
                     (const SfsClientRequestT *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sfs_client_request_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sfs_client_request_t__pack
                     (const SfsClientRequestT *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sfs_client_request_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sfs_client_request_t__pack_to_buffer
                     (const SfsClientRequestT *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sfs_client_request_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SfsClientRequestT *
       sfs_client_request_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SfsClientRequestT *)
     protobuf_c_message_unpack (&sfs_client_request_t__descriptor,
                                allocator, len, data);
}
void   sfs_client_request_t__free_unpacked
                     (SfsClientRequestT *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sfs_client_request_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor sfs_client_request_hdr__field_descriptors[2] =
{
  {
    "magic",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SfsClientRequestHdr, magic),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SfsClientRequestHdr, type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sfs_client_request_hdr__field_indices_by_name[] = {
  0,   /* field[0] = magic */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange sfs_client_request_hdr__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sfs_client_request_hdr__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "sfs_client_request_hdr",
  "SfsClientRequestHdr",
  "SfsClientRequestHdr",
  "",
  sizeof(SfsClientRequestHdr),
  2,
  sfs_client_request_hdr__field_descriptors,
  sfs_client_request_hdr__field_indices_by_name,
  1,  sfs_client_request_hdr__number_ranges,
  (ProtobufCMessageInit) sfs_client_request_hdr__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor branch_struct_cli__field_descriptors[2] =
{
  {
    "branches",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(BranchStructCli, branches),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "login_name",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(BranchStructCli, login_name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned branch_struct_cli__field_indices_by_name[] = {
  0,   /* field[0] = branches */
  1,   /* field[1] = login_name */
};
static const ProtobufCIntRange branch_struct_cli__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor branch_struct_cli__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "branch_struct_cli",
  "BranchStructCli",
  "BranchStructCli",
  "",
  sizeof(BranchStructCli),
  2,
  branch_struct_cli__field_descriptors,
  branch_struct_cli__field_indices_by_name,
  1,  branch_struct_cli__number_ranges,
  (ProtobufCMessageInit) branch_struct_cli__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor policy_struct_cli__field_descriptors[6] =
{
  {
    "fname",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PolicyStructCli, fname),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ftype",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PolicyStructCli, ftype),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uid",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PolicyStructCli, uid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gid",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PolicyStructCli, gid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hidden",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PolicyStructCli, hidden),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "qoslevel",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PolicyStructCli, qoslevel),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned policy_struct_cli__field_indices_by_name[] = {
  0,   /* field[0] = fname */
  1,   /* field[1] = ftype */
  3,   /* field[3] = gid */
  4,   /* field[4] = hidden */
  5,   /* field[5] = qoslevel */
  2,   /* field[2] = uid */
};
static const ProtobufCIntRange policy_struct_cli__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor policy_struct_cli__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "policy_struct_cli",
  "PolicyStructCli",
  "PolicyStructCli",
  "",
  sizeof(PolicyStructCli),
  6,
  policy_struct_cli__field_descriptors,
  policy_struct_cli__field_indices_by_name,
  1,  policy_struct_cli__number_ranges,
  (ProtobufCMessageInit) policy_struct_cli__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sfs_client_request_t__field_descriptors[3] =
{
  {
    "hdr",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SfsClientRequestT, hdr),
    &sfs_client_request_hdr__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "u1",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SfsClientRequestT, u1),
    &branch_struct_cli__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "u2",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SfsClientRequestT, u2),
    &policy_struct_cli__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sfs_client_request_t__field_indices_by_name[] = {
  0,   /* field[0] = hdr */
  1,   /* field[1] = u1 */
  2,   /* field[2] = u2 */
};
static const ProtobufCIntRange sfs_client_request_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor sfs_client_request_t__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "sfs_client_request_t",
  "SfsClientRequestT",
  "SfsClientRequestT",
  "",
  sizeof(SfsClientRequestT),
  3,
  sfs_client_request_t__field_descriptors,
  sfs_client_request_t__field_indices_by_name,
  1,  sfs_client_request_t__number_ranges,
  (ProtobufCMessageInit) sfs_client_request_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
